export * from "./header";
export * from "./hero/";
export * from "./about-us";
export * from "./category";
export * from "./popular-products";
export * from "./products-life";
export * from "./partners";
export * from "./contacts";
export * from "./footer";
